"""30 diverse SoCal homeowner personas for synthetic depth interviews.

Personas are deliberately NOT tied to the 5 existing market segments —
the goal is to discover segments organically from interview data.
"""

INTERVIEW_PERSONAS = [
    # --- Assigned to GPT-4.1-mini (odd indices 0,2,4,...28 after interleave) ---
    # --- Assigned to Gemini-2.5-Flash (even indices 1,3,5,...29 after interleave) ---
    {
        "persona_id": "INT01", "name": "Jordan",
        "age": "25-34", "income": "$75,000-$99,999",
        "work_arrangement": "I work remotely full-time (5 days/week from home)",
        "home_situation": "2-bedroom condo with small patio in Long Beach",
        "household": "Lives alone with a dog",
        "lifestyle_note": "Avid podcast listener who dabbles in music production on weekends.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT02", "name": "Taylor",
        "age": "35-44", "income": "$150,000-$199,999",
        "work_arrangement": "I work a hybrid schedule (at least part of my week is remote)",
        "home_situation": "4-bedroom house with medium backyard in Pasadena",
        "household": "Married, two kids (ages 4 and 7)",
        "lifestyle_note": "Weekend trail runner who coaches kids' soccer.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT03", "name": "Morgan",
        "age": "45-54", "income": "$200,000 or more",
        "work_arrangement": "I am self-employed / freelance (primarily work from home)",
        "home_situation": "5-bedroom house with large backyard in Claremont",
        "household": "Married, one teenager, aging parent lives in guest room",
        "lifestyle_note": "Runs a consulting business and collects mid-century modern furniture.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT04", "name": "Casey",
        "age": "25-34", "income": "$50,000-$74,999",
        "work_arrangement": "I work on-site / in-person full-time",
        "home_situation": "3-bedroom townhome with tiny backyard in Pomona",
        "household": "Lives with partner",
        "lifestyle_note": "Mountain biker who spends weekends at local trails and wrenches on bikes in the garage.",
        "hoa_status": "I'm not sure",
    },
    {
        "persona_id": "INT05", "name": "Avery",
        "age": "55-64", "income": "$100,000-$149,999",
        "work_arrangement": "I am retired",
        "home_situation": "3-bedroom ranch house with large backyard in Glendora",
        "household": "Married, empty nester, grandkids visit monthly",
        "lifestyle_note": "Passionate gardener who also does watercolor painting.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT06", "name": "Riley",
        "age": "35-44", "income": "$100,000-$149,999",
        "work_arrangement": "I work remotely full-time (5 days/week from home)",
        "home_situation": "3-bedroom house with medium backyard in Rancho Cucamonga",
        "household": "Single parent, one child (age 9)",
        "lifestyle_note": "Yoga practitioner who journals daily and is exploring meditation retreats.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT07", "name": "Quinn",
        "age": "25-34", "income": "$75,000-$99,999",
        "work_arrangement": "I work a hybrid schedule (at least part of my week is remote)",
        "home_situation": "2-bedroom house with small backyard in Azusa",
        "household": "Lives with two roommates",
        "lifestyle_note": "Aspiring content creator who films YouTube videos and needs quiet recording space.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT08", "name": "Dakota",
        "age": "45-54", "income": "$150,000-$199,999",
        "work_arrangement": "I work on-site / in-person full-time",
        "home_situation": "4-bedroom house with large backyard in Arcadia",
        "household": "Married, three kids (ages 6, 10, 13)",
        "lifestyle_note": "Real estate hobbyist who follows property values closely and hosts backyard BBQs.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT09", "name": "Reese",
        "age": "35-44", "income": "$100,000-$149,999",
        "work_arrangement": "I am self-employed / freelance (primarily work from home)",
        "home_situation": "3-bedroom house with medium backyard in Monrovia",
        "household": "Married, no kids, two cats",
        "lifestyle_note": "Freelance graphic designer who needs a dedicated studio space away from distractions.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT10", "name": "Skyler",
        "age": "25-34", "income": "$50,000-$74,999",
        "work_arrangement": "I work on-site / in-person full-time",
        "home_situation": "2-bedroom condo with balcony and shared courtyard in Ontario",
        "household": "Lives with partner and infant",
        "lifestyle_note": "DIY enthusiast who watches home improvement shows and loves budget hacks.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT11", "name": "Jamie",
        "age": "45-54", "income": "$200,000 or more",
        "work_arrangement": "I work a hybrid schedule (at least part of my week is remote)",
        "home_situation": "5-bedroom house with pool and large backyard in San Dimas",
        "household": "Married, two teenagers",
        "lifestyle_note": "Fitness enthusiast with a home gym setup who also hosts poker nights.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT12", "name": "Drew",
        "age": "35-44", "income": "$75,000-$99,999",
        "work_arrangement": "I work remotely full-time (5 days/week from home)",
        "home_situation": "3-bedroom house with small backyard in West Covina",
        "household": "Married, one toddler",
        "lifestyle_note": "Software developer who games at night and needs better work-life separation.",
        "hoa_status": "I'm not sure",
    },
    {
        "persona_id": "INT13", "name": "Sage",
        "age": "55-64", "income": "$150,000-$199,999",
        "work_arrangement": "I am retired",
        "home_situation": "4-bedroom house with large backyard in La Verne",
        "household": "Married, empty nester",
        "lifestyle_note": "Avid reader and amateur woodworker who dreams of a proper workshop.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT14", "name": "Rowan",
        "age": "25-34", "income": "$100,000-$149,999",
        "work_arrangement": "I work a hybrid schedule (at least part of my week is remote)",
        "home_situation": "3-bedroom house with medium backyard in Upland",
        "household": "Lives with partner",
        "lifestyle_note": "Rock climber and outdoor photographer who needs gear storage and an editing station.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT15", "name": "Emery",
        "age": "35-44", "income": "$100,000-$149,999",
        "work_arrangement": "I work on-site / in-person full-time",
        "home_situation": "3-bedroom house with medium backyard in Covina",
        "household": "Married, two kids (ages 3 and 6)",
        "lifestyle_note": "Scouts leader who values family outdoor time and is always looking for activity space.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT16", "name": "Cameron",
        "age": "45-54", "income": "$100,000-$149,999",
        "work_arrangement": "I work remotely full-time (5 days/week from home)",
        "home_situation": "4-bedroom house with medium backyard in Diamond Bar",
        "household": "Married, one teenager, one college student",
        "lifestyle_note": "Accountant who meditates and wants separation between work and home life.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT17", "name": "Hayden",
        "age": "25-34", "income": "$50,000-$74,999",
        "work_arrangement": "I work on-site / in-person full-time",
        "home_situation": "2-bedroom apartment with shared backyard in El Monte",
        "household": "Lives with sibling",
        "lifestyle_note": "Musician who plays guitar and wants somewhere to practice without bothering neighbors.",
        "hoa_status": "I'm not sure",
    },
    {
        "persona_id": "INT18", "name": "Parker",
        "age": "35-44", "income": "$150,000-$199,999",
        "work_arrangement": "I am self-employed / freelance (primarily work from home)",
        "home_situation": "4-bedroom house with large backyard in Chino Hills",
        "household": "Married, three kids (ages 2, 5, 8)",
        "lifestyle_note": "Runs an e-commerce business from home and needs inventory storage and shipping space.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT19", "name": "Finley",
        "age": "55-64", "income": "$75,000-$99,999",
        "work_arrangement": "I am retired",
        "home_situation": "3-bedroom house with large backyard in Duarte",
        "household": "Lives alone, widowed",
        "lifestyle_note": "Active in community volunteering, enjoys birdwatching and reading in the garden.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT20", "name": "Peyton",
        "age": "25-34", "income": "$100,000-$149,999",
        "work_arrangement": "I work a hybrid schedule (at least part of my week is remote)",
        "home_situation": "3-bedroom house with small backyard in Alhambra",
        "household": "Married, expecting first child",
        "lifestyle_note": "Couple who loves hosting dinner parties and is nesting before the baby arrives.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT21", "name": "Kendall",
        "age": "35-44", "income": "$75,000-$99,999",
        "work_arrangement": "I work on-site / in-person full-time",
        "home_situation": "3-bedroom house with medium backyard in Baldwin Park",
        "household": "Single parent, two kids (ages 8 and 11)",
        "lifestyle_note": "Nurse who works long shifts and craves a personal sanctuary at home for decompression.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT22", "name": "Tatum",
        "age": "45-54", "income": "$200,000 or more",
        "work_arrangement": "I work a hybrid schedule (at least part of my week is remote)",
        "home_situation": "5-bedroom house with large backyard and pool in Yorba Linda",
        "household": "Married, two teenagers",
        "lifestyle_note": "Executive who entertains clients at home and wants an impressive, private meeting space.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT23", "name": "Blake",
        "age": "25-34", "income": "$75,000-$99,999",
        "work_arrangement": "I work remotely full-time (5 days/week from home)",
        "home_situation": "2-bedroom house with small backyard in Whittier",
        "household": "Lives with partner and rescue dog",
        "lifestyle_note": "Surfer and environmentalist who values sustainability in home products.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT24", "name": "Marley",
        "age": "35-44", "income": "$100,000-$149,999",
        "work_arrangement": "I work on-site / in-person full-time",
        "home_situation": "3-bedroom house with medium backyard in Walnut",
        "household": "Married, one child (age 5)",
        "lifestyle_note": "Teacher who tutors on the side and wants a quiet space for evening tutoring sessions.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT25", "name": "Remy",
        "age": "55-64", "income": "$100,000-$149,999",
        "work_arrangement": "I am self-employed / freelance (primarily work from home)",
        "home_situation": "4-bedroom house with large backyard in Claremont",
        "household": "Married, adult children visit often",
        "lifestyle_note": "Part-time consultant and potter who fires ceramics in the garage.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT26", "name": "Ellis",
        "age": "25-34", "income": "$50,000-$74,999",
        "work_arrangement": "I work a hybrid schedule (at least part of my week is remote)",
        "home_situation": "2-bedroom townhome with tiny backyard in Fontana",
        "household": "Lives with partner",
        "lifestyle_note": "Gamer and streamer who needs a dedicated setup away from the shared living space.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT27", "name": "Lennox",
        "age": "35-44", "income": "$150,000-$199,999",
        "work_arrangement": "I work remotely full-time (5 days/week from home)",
        "home_situation": "4-bedroom house with medium backyard in Brea",
        "household": "Married, one child (age 2)",
        "lifestyle_note": "Tech lead who takes video calls all day and needs soundproofing from household noise.",
        "hoa_status": "Yes",
    },
    {
        "persona_id": "INT28", "name": "Phoenix",
        "age": "45-54", "income": "$75,000-$99,999",
        "work_arrangement": "I work on-site / in-person full-time",
        "home_situation": "3-bedroom house with medium backyard in Riverside",
        "household": "Married, two kids (ages 12 and 15)",
        "lifestyle_note": "Coach and fitness trainer who does personal training sessions and wants a private gym.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT29", "name": "Kai",
        "age": "25-34", "income": "$100,000-$149,999",
        "work_arrangement": "I am self-employed / freelance (primarily work from home)",
        "home_situation": "3-bedroom house with medium backyard in Redlands",
        "household": "Lives alone",
        "lifestyle_note": "Freelance videographer who needs a climate-controlled editing suite and equipment storage.",
        "hoa_status": "No",
    },
    {
        "persona_id": "INT30", "name": "Sage R.",
        "age": "35-44", "income": "$75,000-$99,999",
        "work_arrangement": "I work a hybrid schedule (at least part of my week is remote)",
        "home_situation": "3-bedroom house with small backyard in San Bernardino",
        "household": "Married, one child (age 7), elderly mother visits frequently",
        "lifestyle_note": "Crafts seller on Etsy who needs workspace for inventory and shipping.",
        "hoa_status": "I'm not sure",
    },
]

# Model assignment: interleaved so each model gets diverse cross-section
MODEL_ASSIGNMENTS = {
    "openai/gpt-4.1-mini": [p for i, p in enumerate(INTERVIEW_PERSONAS) if i % 2 == 0],
    "google/gemini-2.5-flash": [p for i, p in enumerate(INTERVIEW_PERSONAS) if i % 2 == 1],
}

MODEL_LABELS = {
    "openai/gpt-4.1-mini": "GPT-4.1-mini",
    "google/gemini-2.5-flash": "Gemini-2.5-Flash",
}
