[theme]
primaryColor = "#005394"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#f2f4f7"
textColor = "#191c1e"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
